version: '3.8'
services:
  backend:
    container_name: main_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db
      
  db:
    image: mysql:8.0
    container_name: main_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
      MYSQL_USER: django
      MYSQL_PASSWORD: django
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33061:3306"