version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
      
  db:
    image: mysql:8.0
    container_name: mysql8-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin
      MYSQL_USER: django
      MYSQL_PASSWORD: django
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33060:3306"